[project]
name = "pro-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
pro-3 = "pro_3:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
